### ISSUE TITLE
Optionlarni JSdan turib qo'shish

### ISSUE THREAD

**Issue by ozbeg** [xojiakbar0305/sort-movies#1]
https://github.com/xojiakbar0305/sort-movies/blob/14f02bfadeacb828ec565edcdc40cf7283174843/index.html#L21

optionlarni agarda js da arraydan turib qo'shsangiz har doim ham HTMLni be'zovta qilmaysiz 💯

**Comment by xojiakbar0305** [comment]
bu o'zgarmas select-ku
